import discord
import datetime
import random
from discord.ext import commands

class Help(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        bot.remove_command('help')  #remove the built-in help command

    @commands.group(case_insensitive=True)  #a group of subcommands which offers informations about the commands of the bot
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def help(self, ctx):  #the main help command
        if ctx.invoked_subcommand is None:  #if help about a specific command is not requested ('{ctx.prefix}help', not '{ctx.prefix}help some_command')
            embed = discord.Embed(title='Totally not a Rickroll', url='https://www.youtube.com/watch?v=dQw4w9WgXcQ', description=f'Use `{ctx.prefix}help [command]` for details', color=0xff0000, timestamp=datetime.datetime.utcnow())
            embed.set_author(name='Kanemki Command List', icon_url=self.bot.user.avatar_url)
            embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/726569752906170408/kanemki.png')        
            embed.set_footer(icon_url='https://cdn.discordapp.com/attachments/725102631185547427/726098955456479293/The_Watcher_New.png', text='Developed by RobertCDR#2573')
            embed.add_field(name=':grin: Fun', value=f'`{ctx.prefix}help fun`', inline=True)
            embed.add_field(name=':video_game: Games', value=f'`{ctx.prefix}help games`', inline=True)
            embed.add_field(name=":alien: Memes'n'stuff", value=f'`{ctx.prefix}help memes`')
            embed.add_field(name=':camera: Images', value=f'`{ctx.prefix}help images`', inline=True)
            embed.add_field(name=':sparkles: Actions', value=f'`{ctx.prefix}help actions`', inline=True)
            embed.add_field(name=':frog: Animals', value=f'`{ctx.prefix}help animals`', inline=True)
            embed.add_field(name=':heavy_plus_sign: Math', value=f'`{ctx.prefix}help math`', inline=True)
            embed.add_field(name=':bulb: Utilities', value=f'`{ctx.prefix}help utils`', inline=True)
            embed.add_field(name=':hammer: Moderation', value=f'`{ctx.prefix}help mod`', inline=True)
            await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def fun(self, ctx):
        embed = discord.Embed(title=':grin: Fun Commands', description='`fuck`, `sex`, `pula`, `ask`, `gayrate`, `love`, `hack`, `say`, `clapify`, `spoilify`, `lewdify`, `texttomorse`, `morsetotext`, `age`, `embed`, `pun`, `roast`, `fookie`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def games(self, ctx):
        embed = discord.Embed(title=':video_game: Games Commands', description='`flip`, `roll`, `rockpaperscissors`, `guess`, `truthordare`, `hangman`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def memes(self, ctx):
        embed = discord.Embed(title=':alien: Memes n Stuff Commands', description='`meme`, `wholesome`, `rareinsult`, `cursedcomment`, `holup`, `blursed`, `cursed`, `fifty`, `facts`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def images(self, ctx):
        embed = discord.Embed(title=':camera: Images Commands', description='`pfp`, `spotify`, `award`, `xkcd`, `color`, `battlestation`, `flower`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def actions(self, ctx):
        embed = discord.Embed(title=':sparkles: Action Commands', description='`gif`, `facepalm`, `shrug`, `cry`, `run`, `tongue`, `point`, `hug`, `kiss`, `slap`, `punch`, `wink`, `stare`, `lick`, `bite`, `cuddle`, `pat`, `smile`, `poke`, `tickle`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_author(icon_url='https://cdn.discordapp.com/attachments/725102631185547427/735969171984351292/giphy.png', name='Powered by GIPHY')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def animals(self, ctx):
        embed = discord.Embed(title=':frog: Animals Commands', description='`eyebleach`, `dog`, `cat`, `rabbit`, `bear`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def math(self, ctx):
        embed = discord.Embed(title=':heavy_plus_sign: Math Commands', description='`sum`, `diff`, `multy`, `div`, `pow`, `sqrt`, `log2`, `lg`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def utils(self, ctx):
        embed = discord.Embed(title=':bulb: Utilities Commands', description='`help`, `ping`, `userinfo`, `serverinfo`, `roleinfo`, `permissions`, `rpermissions`, `passwordgen`, `search`, `urban`, `coronavirus`, `todo`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def mod(self, ctx):
        embed = discord.Embed(title=':hammer: Moderation Commands', description='`config`, `roles`, `clear`, `mute`, `unmute`, `kick`, `softban`, `ban`, `unban`, `unbanall`', color=random.randint(0, 0xffffff), timestamp=datetime.datetime.utcnow())
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['frick'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def fuck(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nhave some fun with your friends', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='fuck command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}fuck @user')
        embed.add_field(name='**Aliases**', value='frick', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def sex(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nprobably every single message is true (excepting the ones that involve more than one person)', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='sex command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}sex')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['pp', 'ppsize', 'penis'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def pula(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nvalues over 20 are real only in porn', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='pula command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}pula or {ctx.prefix}pula @user')
        embed.add_field(name='**Aliases**', value='pp, ppsize, penis', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['8ball'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def ask(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nresponds to your questions through magic voodoo shit', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='ask command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}8ball `question`')
        embed.add_field(name='**Aliases**', value='ask', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['gay', 'howgay', 'gayr8'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def gayrate(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows how gay you are deep inside yourself', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='gayrate command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}gayrate or {ctx.prefix}gayrate @user')
        embed.add_field(name='**Aliases**', value='gay, howgay, gayr8', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['ship', 'lovemeter', 'compatibility'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def love(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nThe ultimate and most revolutionary Love Machine', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='love command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}love @user')
        embed.add_field(name='**Aliases**', value='ship, lovemeter, compatibility', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def hack(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nWe are Anonymous. We are legion. We do not forget. We do not forgive. Expect us.', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='hack command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}hack @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`20s/user`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['parrot', 'mimic', 'repeat'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def say(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nmake the bot say everything you want (Detroit: Become Human shit)', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='say command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}say `something`')
        embed.add_field(name='**Aliases**', value='parrot, mimic, repeat', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def clapify(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nmake your message be extremely sarcastic or over enthusiastic', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='clapify command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}clapify `something`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def spoilify(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nencrypt your message to annoy someone (for long-"posterior" texts Satan has a spot waiting just for you)', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='spoilify command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}spoilify `something`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def lewdify(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ncan someone please tell me why I coded this?', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='lewdify command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}lewdify `something`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No, just cringe')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['tomorse'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def texttomorse(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ntranslate text into Morse code', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='texttomorse command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}texttomorse `something`')
        embed.add_field(name='**Aliases**', value='tomorse', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['totext'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def morsetotext(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ntranslate Morse code into text', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='morsetotext command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}morsetotext `something`')
        embed.add_field(name='**Aliases**', value='totext', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['age', 'howmanydays'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def agedays(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nsee how many days old are you", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='age command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}age `dd`/`mm`/`yyyy`')
        embed.add_field(name='**Aliases**', value='agedays, howmanydays', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['emb'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def embed(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\ncreate a custom embed", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='embed command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}embed `param1, param2...`\n\nParameters:\n**title**(t)=text\n**description**(descr, d)=text\n**author**=text\n**footer**=text\n**thumbnail**(thumb, tn)=link\n**image**(img, i)=link\n**time**')
        embed.add_field(name='**Aliases**', value='emb', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def pun(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nyou literally don't have anything better to do if you're using this command, am I right?", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='pun command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}pun')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def roast(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nroast someone or yourself", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='roast command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}roast or {ctx.prefix}roast @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['fortunecookie', 'fortune'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def fookie(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nyes, fortune cookies, let's see what you get", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='fookie command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}fookie')
        embed.add_field(name='**Aliases**', value='fortunecookie, fortune', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def flip(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nheads or tails', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='flip command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}flip')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['dice'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def roll(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nroll the dices', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='roll command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}roll')
        embed.add_field(name='**Aliases**', value='dice', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['rockpaperscissors'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def rps(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nduel with someone in the ultimate battle', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='rockpaperscissors command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}rockpaperscissors `choice` @user')
        embed.add_field(name='**Aliases**', value='rps', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def guess(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nguess random numbers', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='guess command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}guess or {ctx.prefix}guess `number`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['tod'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def truthordare(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nplay Truth or Dare with your friends', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='truthordare command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}truthordare')
        embed.add_field(name='**Aliases**', value='tod', inline=False)
        embed.add_field(name='**Cooldown**', value='2s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['hman', 'hang'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def hangman(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nplay a game of Hangman by yourself or with your friends', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='hangman command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}hangman or {ctx.prefix}hangman @users')
        embed.add_field(name='**Aliases**', value='hang, hman', inline=False)
        embed.add_field(name='**Cooldown**', value='30s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def meme(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget memes from reddit', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='meme command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}meme')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['whlsm', 'wholesomeme', 'wmeme'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def wholesome(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a wholesome meme', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='wholesome command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}wholesome')
        embed.add_field(name='**Aliases**', value='whlsm, wholesomeme, wmeme', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['rinsult', 'rareins'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def rareinsult(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsee the creativity of internet people when it comes to insults', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='rareinsult command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}rareinsult')
        embed.add_field(name='**Aliases**', value='rareins, rinsult', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['cursedcom', 'ccom'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def cursedcomment(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsee how sick are some people and wonder what it is gonna be of the humanity', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='cursedcomment command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}cursedcomment')
        embed.add_field(name='**Aliases**', value='cursedcom, ccom', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='Only if you imagine it I guess (anyway, do not imagine, take it as an advice)')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['holdup'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def holup(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nthe name speaks for itself', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='holup command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}holup')
        embed.add_field(name='**Aliases**', value='holdup', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='Not really')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def blursed(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows a blursed image (a cursed but no so cursed image)', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='blursed command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}blursed')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def cursed(self, ctx):    
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows a cursed image', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='cursed command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}cursed')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='Not necessarily with small exceptions')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['50/50', 'fifty'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def fiftyfifty(self, ctx):    
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nr/FiftyFifty - may God take care of you and erase the horrible things that you see from your memory', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='fifty command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}fifty')
        embed.add_field(name='**Aliases**', value='fiftyfifty, 50/50', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='YES IT IS VERY NSFW')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['fact', 'fax'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def facts(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget random facts from r/facts', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='facts command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}facts')
        embed.add_field(name='**Aliases**', value='fact, fax', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def pfp(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nshows your avatar or someone else's", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='pfp command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}pfp or {ctx.prefix}pfp @user')
        embed.add_field(name='**Aliases**', value='av, avatar', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def spotify(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nif you've found yourself in the situation of wanting to get the cover art of a Spotify track, this command can help you out (it literally does nothing more)", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='spotify command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}spotify or {ctx.prefix}spotify @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def award(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\naward someone for whatever reason it goes through your head', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='award command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value='{ctx.prefix}award @user `reason`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def xkcd(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a comic from [xkcd.com](https://xkcd.com)', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='xkcd command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}xkcd or {ctx.prefix}xkcd `comic number`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['colour'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def color(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nvisualize a hex color', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='color command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}color `hex`')
        embed.add_field(name='**Aliases**', value='colour', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['nasapc', 'wowsetup', 'rocketpc'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def battlestation(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsee some good looking pc setups', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='battlestation command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}battlestation')
        embed.add_field(name='**Aliases**', value='nasapc, wowsetup, rocketpc', inline=False)
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def flower(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows a flower', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='flower command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}flower')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def gif(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a gif from GIPHY', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='gif command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}gif `search`')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def facepalm(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a facepalm gif', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='facepalm command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}facepalm')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def shrug(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a shrug gif', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='shrug command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}shrug')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def cry(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a cry gif', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='cry command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}cry')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def pout(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a pout gif', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='pout command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}pout')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def run(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a run gif', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='run command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}run')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def tongue(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a tongue out gif', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='tongue command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}tongue')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def hug(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nhug someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='hug command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}hug @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def point(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nfinger point someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='hug command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}point @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def punch(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\npunch someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='punch command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}punch @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def kiss(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nkiss someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='kiss command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}kiss @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def slap(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nslap someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='slap command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}slap @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed) 
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def wink(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nwink at someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='wink command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}wink @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def stare(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nstare at someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='stare command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}stare @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def lick(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nlick someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='lick command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}lick @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def bite(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nbite someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='bite command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}bite @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def cuddle(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ncuddle with someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='cuddle command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}cuddle @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def pat(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\npat someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='pat command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}pat @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def smile(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsmile at someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='smile command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}smile @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def poke(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\npoke someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='poke command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}poke @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def tickle(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ntickle someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='tickle command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}tickle @user')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['cute', 'eyebleach'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def aww(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows you cute animals', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='eyebleach command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}eyebleach')
        embed.add_field(name='**Aliases**', value='aww, cute', inline=False)
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['doggo', 'woof', 'doggy'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def dog(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows you a dog', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='dog command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}dog')
        embed.add_field(name='**Aliases**', value='doggo, woof, doggy', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['kitty', 'meow', 'kat'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def cat(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows you a cat', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='cat command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}cat')
        embed.add_field(name='**Aliases**', value='kitty, meow, kat', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['bunny', 'bunbun', 'bun', 'longears'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def rabbit(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows you a rabbit', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='rabbit command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}rabbit')
        embed.add_field(name='**Aliases**', value='bunny, bunbun, bun, longears', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def bear(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows you a bear', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='bear command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}bear')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['sum'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def add(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsum numbers', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='sum command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}sum `numbers` (no numbers limit)')
        embed.add_field(name='**Aliases**', value='add', inline=False)
        embed.add_field(name='**Cooldown**', value='``')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['reduce', 'subtract'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def diff(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsubtract numbers', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='diff command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}diff `nr1` `nr2`')
        embed.add_field(name='**Aliases**', value='reduce, subtract', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['multiply', 'times'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def multy(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nmultiply numbers', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='multy command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}multy `numbers` (no numbers limit)')
        embed.add_field(name='**Aliases**', value='multiply, times', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['div'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def divide(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ndivide numbers', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='div command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}div `nr1` `nr2`')
        embed.add_field(name='**Aliases**', value='divide', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['pow'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def power(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nraise to power', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='pow command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}pow `nr1` `nr2`')
        embed.add_field(name='**Aliases**', value='power', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['squareroot'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def sqrt(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsquare root of a number', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='sqrt command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}sqrt `nr`')
        embed.add_field(name='**Aliases**', value='squareroot', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['logarithm2'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def log2(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nbase 2 logarithm of a number', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='log2 command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}log2 `nr`')
        embed.add_field(name='**Aliases**', value='logarithm2', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['logarithm10', 'log10'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def lg(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nbase 10 logarithm of a number', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='lg command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}lg `nr`')
        embed.add_field(name='**Aliases**', value='logarithm10, log10', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def invite(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget an invite link to invite the bot to your server', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='ping command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}invite')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def ping(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nbot latency', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='ping command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}ping')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['uinfo', 'about', 'whois'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def userinfo(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget info about yourself or someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='userinfo command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}userinfo or {ctx.prefix}userinfo @user')
        embed.add_field(name='**Aliases**', value='uinfo, about, whois', inline=False)
        embed.add_field(name='**Cooldown**', value='2s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['sinfo', 'aboutsrv'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def serverinfo(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget info about the server', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='serverinfo command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}serverinfo')
        embed.add_field(name='**Aliases**', value='sinfo, aboutsrv', inline=False)
        embed.add_field(name='**Cooldown**', value='2s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['rinfo'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def roleinfo(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget info about a role', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='roleinfo command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}roleinfo `role` (make sure to write the exact role name) or {ctx.prefix}roleinfo @role')
        embed.add_field(name='**Aliases**', value='rinfo', inline=False)
        embed.add_field(name='**Cooldown**', value='2s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['perms', 'userperms'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def permissions(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a list of guild permissions someone has', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='permissions command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}permissions or {ctx.prefix}permissions @user')
        embed.add_field(name='**Aliases**', value='perms, userperms', inline=False)
        embed.add_field(name='**Cooldown**', value='2s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['rperms', 'roleperms'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def rpermissions(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget a list of permissions for a role', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='rpermissions command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}rpermissions `role` (make sure to write the exact role name) or {ctx.prefix}rpermissions @role')
        embed.add_field(name='**Aliases**', value='rperms, roleperms', inline=False)
        embed.add_field(name='**Cooldown**', value='2s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['passgen', 'password'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def passwordgen(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ngenerate a random password for whatever use you want', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='passwordgen command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}passwordgen `length` `use`\n\n*The length (how long the password will be) and use (for what will you use it) parameters are optional.*')
        embed.add_field(name='**Aliases**', value='passgen, password', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['lmgtfy'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def search(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description="**Description**\nfor every person that's tired of someone's stupid questions or too lazy to switch tabs", timestamp=datetime.datetime.utcnow())
        embed.set_author(name='search command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}search `search`')
        embed.add_field(name='**Aliases**', value='lmgtfy', inline=False)
        embed.add_field(name='**Cooldown**', value='3s/user')
        embed.add_field(name='**NSFW**', value='Depends on what you search')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['urbandict', 'urbandic', 'urbdic', 'urbdict'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def urban(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nget the urban definition of a word from Urban Dictionary', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='urban command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}urban `word`')
        embed.add_field(name='**Aliases**', value='urbandict, urbandic, urbdic, urbdict', inline=False)
        embed.add_field(name='**Cooldown**', value='10s/user')
        embed.add_field(name='**NSFW**', value='Depends on what you search')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['covid19', 'sarscov2'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def coronavirus(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nCountry statistics for COVID-19', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='coronavirus command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}coronavirus `country`\n(make sure that you write it in english)')
        embed.add_field(name='**Aliases**', value='covid19, sarscov2', inline=False)
        embed.add_field(name='**Cooldown**', value='10s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['help'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def _help(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\ndisplays a list of categories of commands', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='help command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}help')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='1s/user')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def roles(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nshows a list of all roles in the guild', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='roles command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}roles')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['purge', 'clean'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def clear(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nclears an amount of messages', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='clear command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}clear `amount`')
        embed.add_field(name='**Aliases**', value='purge, clean', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def mute(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nmute someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='mute command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}mute @user(s) `duration` `reason`\nDuration format: *number*`s`/`m`/`h`/`d`/`w`\n*This command can be used for mass muting.*')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def unmute(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nunmute someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='unmute command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}unmute @user(s)\n*This command can be used for mass unmuting.*')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def kick(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nkick someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='kick command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}mute @user(s) `reason`\n*This command can be used for mass kicking.*')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def ban(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nban someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='ban command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}ban @user(s) `reason` or {ctx.prefix}ban `user id` `reason`\n*This command can be used for mass banning.*')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command(aliases=['tempban'])
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def softban(self, ctx):
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nsoftban someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='softban command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}softban @user `duration` `reason`\nDuration format: *number*`h`/`d`/`w`/`m`/`y`')
        embed.add_field(name='**Aliases**', value='tempban', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def unban(self, ctx):    
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nunban someone', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='unban command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}unban `user id`\n*This command can be used for mass unbanning.*')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)
    @help.command()
    @commands.cooldown(1, 1, commands.BucketType.user)
    async def unbanall(self, ctx):    
        embed = discord.Embed(color=random.randint(0, 0xffffff), description='**Description**\nunban all guild users (server administrator only command)', timestamp=datetime.datetime.utcnow())
        embed.set_author(name='unbanall command help', icon_url=self.bot.user.avatar_url)
        embed.set_thumbnail(url='https://cdn.discordapp.com/attachments/725102631185547427/740546485560803450/question.png')
        embed.add_field(name='**Usage**', value=f'{ctx.prefix}unbanall')
        embed.add_field(name='**Aliases**', value='`None`', inline=False)
        embed.add_field(name='**Cooldown**', value='`None`')
        embed.add_field(name='**NSFW**', value='No')
        embed.set_footer(icon_url=ctx.message.author.avatar_url, text=f'Requested by {str(ctx.message.author)}')
        await ctx.send(embed=embed)

def setup(bot):
    bot.add_cog(Help(bot))